# Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: nicolaslazzos/auth
          imagePullPolicy: Never
          env:
            # for setting a secret => kubectl create secret generic jwt-secret --from-literal=JWT_KEY=some_key
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
# NodePort service

apiVersion: v1
kind: Service
metadata:
  name: auth-serv
spec:
  type: NodePort
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
