# Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
        - name: tickets
          image: nicolaslazzos/tickets
          imagePullPolicy: Never
          env:
            - name: MONGO_URI
              value: mongodb://tickets-mongo-serv:27017/tickets
            # for setting a secret => kubectl create secret generic jwt-secret --from-literal=JWT_KEY=some_key
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
# NodePort service

apiVersion: v1
kind: Service
metadata:
  name: tickets-serv
spec:
  type: NodePort
  selector:
    app: tickets
  ports:
    - name: tickets
      protocol: TCP
      port: 3000
      targetPort: 3000
