name: deploy-client

on:
  push:
    branches:
      - master
    paths:
      - 'client/**'
      
jobs:
  build:
    # already comes with docker installed
    runs-on: ubuntu-latest
    steps:
      # check out all of the code in the repo
      - uses: actions/checkout@v2
      - run: cd client && docker build -t nicolaslazzos/client .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          # this secrets should be set in the github repo settings
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push nicolaslazzos/client
      # this is for deploying it to digital ocean, not doing it for now
      # - uses: digitalocean/action-doctl@v2
      #   with:
      #   token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      # - run: doctl kubernetes cluster kubeconfig save CLUSTER_NAME_HERE
      # - run: kubectl rollout restart deployment client-depl
