name: deploy-auth

on:
  push:
    branches:
      - master
    paths:
      - 'auth/**'
      
jobs:
  build:
    # already comes with docker installed
    runs-on: ubuntu-latest
    steps:
      # check out all of the code in the repo
      - uses: actions/checkout@v2
      - run: cd auth && docker build -t nicolaslazzos/auth .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          # this secrets should be set in the github repo settings
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push nicolaslazzos/auth
